// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType]
}
/** Content for Homepage documents */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter page title
   * - **API ID Path**: homepage.title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField
  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tell search engines what you do
   * - **API ID Path**: homepage.metadescription
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  metadescription: prismic.KeyTextField
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice =
  | ContentSlice
  | HerosSlice
  | SeperatorSlice
  | CarousellSlice
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >
/** Content for MainMenu documents */
interface MainmenuDocumentData {
  /**
   * SubMenu field in *MainMenu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mainmenu.submenu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  submenu: prismic.GroupField<Simplify<MainmenuDocumentDataSubmenuItem>>
  /**
   * Slice Zone field in *MainMenu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mainmenu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<MainmenuDocumentDataSlicesSlice>
}
/**
 * Item in MainMenu → SubMenu
 *
 */
export interface MainmenuDocumentDataSubmenuItem {
  /**
   * LinkText field in *MainMenu → SubMenu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mainmenu.submenu[].linktext
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  linktext: prismic.KeyTextField
  /**
   * LinkTarget field in *MainMenu → SubMenu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mainmenu.submenu[].linktarget
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  linktarget: prismic.LinkField
}
/**
 * Slice for *MainMenu → Slice Zone*
 *
 */
type MainmenuDocumentDataSlicesSlice = MenuItemSlice
/**
 * MainMenu document from Prismic
 *
 * - **API ID**: `mainmenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainmenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MainmenuDocumentData>,
    'mainmenu',
    Lang
  >
/** Content for Page documents */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the page title
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField
  /**
   * Subdirectory field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.subdirectory
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  subdirectory: prismic.ContentRelationshipField<'subdirectory'>
  /**
   * Hide Page Title field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: page.hidepagetitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hidepagetitle: prismic.BooleanField
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
  /**
   * MetaDescription field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.metadescription
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  metadescription: prismic.KeyTextField
  /**
   * MetaImage field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.metaimage
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  metaimage: prismic.ImageField<never>
  /**
   * canonical field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.canonical
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  canonical: prismic.KeyTextField
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice =
  | ContentSlice
  | HerosSlice
  | SeperatorSlice
  | CarousellSlice
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>
/** Content for SiteMetadata documents */
interface SitemetadataDocumentData {
  /**
   * SiteTitle field in *SiteMetadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sitemetadata.sitetitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  sitetitle: prismic.KeyTextField
  /**
   * SiteMetaDescription field in *SiteMetadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sitemetadata.sitemetadescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  sitemetadescription: prismic.KeyTextField
  /**
   * SiteMetaImage field in *SiteMetadata*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sitemetadata.sitemetaimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  sitemetaimage: prismic.ImageField<never>
  /**
   * SiteCanonicalUrl field in *SiteMetadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sitemetadata.sitecanonicalurl
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  sitecanonicalurl: prismic.KeyTextField
}
/**
 * SiteMetadata document from Prismic
 *
 * - **API ID**: `sitemetadata`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SitemetadataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SitemetadataDocumentData>,
    'sitemetadata',
    Lang
  >
/** Content for Subdirectory documents */
interface SubdirectoryDocumentData {
  /**
   * Title field in *Subdirectory*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subdirectory.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
}
/**
 * Subdirectory document from Prismic
 *
 * - **API ID**: `subdirectory`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubdirectoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SubdirectoryDocumentData>,
    'subdirectory',
    Lang
  >
export type AllDocumentTypes =
  | HomepageDocument
  | MainmenuDocument
  | PageDocument
  | SitemetadataDocument
  | SubdirectoryDocument
/**
 * Primary content in Carousell → Primary
 *
 */
interface CarousellSliceDefaultPrimary {
  /**
   * content field in *Carousell → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional Title / Paragraph
   * - **API ID Path**: carousell.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField
}
/**
 * Item in Carousell → Items
 *
 */
export interface CarousellSliceDefaultItem {
  /**
   * Images field in *Carousell → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousell.items[].images
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  images: prismic.ImageField<never>
}
/**
 * Default variation for Carousell Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CarousellSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CarousellSliceDefaultPrimary>,
  Simplify<CarousellSliceDefaultItem>
>
/**
 * Primary content in Carousell → Primary
 *
 */
interface CarousellSliceVideoCarouselPrimary {
  /**
   * content field in *Carousell → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional Title / Paragraph
   * - **API ID Path**: carousell.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField
}
/**
 * Item in Carousell → Items
 *
 */
export interface CarousellSliceVideoCarouselItem {
  /**
   * YouTube Vid Link field in *Carousell → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousell.items[].youtube_vid_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  youtube_vid_link: prismic.RichTextField
}
/**
 * Video Carousel variation for Carousell Slice
 *
 * - **API ID**: `videoCarousel`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CarousellSliceVideoCarousel = prismic.SharedSliceVariation<
  'videoCarousel',
  Simplify<CarousellSliceVideoCarouselPrimary>,
  Simplify<CarousellSliceVideoCarouselItem>
>
/**
 * Item in Carousell → Items
 *
 */
export interface CarousellSliceLocationsItem {
  /**
   * Location Item field in *Carousell → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Add the location here
   * - **API ID Path**: carousell.items[].location_item
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  location_item: prismic.RichTextField
  /**
   * Link field in *Carousell → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousell.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField
  /**
   * Link Text field in *Carousell → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousell.items[].link_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  link_text: prismic.KeyTextField
}
/**
 * Locations variation for Carousell Slice
 *
 * - **API ID**: `locations`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CarousellSliceLocations = prismic.SharedSliceVariation<
  'locations',
  Record<string, never>,
  Simplify<CarousellSliceLocationsItem>
>
/**
 * Item in Carousell → Items
 *
 */
export interface CarousellSliceLocationMembersItem {
  /**
   * First Last Name field in *Carousell → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousell.items[].first_last_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  first_last_name: prismic.KeyTextField
  /**
   * phone number field in *Carousell → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousell.items[].phone_number
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  phone_number: prismic.KeyTextField
  /**
   * Job Title field in *Carousell → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousell.items[].job_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  job_title: prismic.KeyTextField
  /**
   * Email field in *Carousell → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousell.items[].email
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  email: prismic.KeyTextField
}
/**
 * locationMembers variation for Carousell Slice
 *
 * - **API ID**: `locationMembers`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CarousellSliceLocationMembers = prismic.SharedSliceVariation<
  'locationMembers',
  Record<string, never>,
  Simplify<CarousellSliceLocationMembersItem>
>
/**
 * Slice variation for *Carousell*
 *
 */
type CarousellSliceVariation =
  | CarousellSliceDefault
  | CarousellSliceVideoCarousel
  | CarousellSliceLocations
  | CarousellSliceLocationMembers
/**
 * Carousell Shared Slice
 *
 * - **API ID**: `carousell`
 * - **Description**: `Carousell`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CarousellSlice = prismic.SharedSlice<
  'carousell',
  CarousellSliceVariation
>
/**
 * Primary content in Content → Primary
 *
 */
interface ContentSliceDefaultPrimary {
  /**
   * Content field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your page content
   * - **API ID Path**: content.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField
}
/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContentSliceDefaultPrimary>,
  never
>
/**
 * Primary content in Content → Primary
 *
 */
interface ContentSliceHalfHalfPrimary {
  /**
   * Reverse This Row field in *Content → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content.primary.reverse_this_row
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  reverse_this_row: prismic.BooleanField
  /**
   * Background Color Toggle field in *Content → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content.primary.hascolor
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hascolor: prismic.BooleanField
  /**
   * Title field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your SubHeading
   * - **API ID Path**: content.primary.titleContent
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  titleContent: prismic.RichTextField
  /**
   * Left Title Optional field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional Title Paragraph
   * - **API ID Path**: content.primary.lefttitleoptional
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  lefttitleoptional: prismic.RichTextField
  /**
   * Left Image Optional field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.leftimageoptional
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  leftimageoptional: prismic.ImageField<never>
  /**
   * lefthalf field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Left half of the content
   * - **API ID Path**: content.primary.lefthalf
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  lefthalf: prismic.RichTextField
  /**
   * Left Button Optional field in *Content → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.leftbuttonoptional
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  leftbuttonoptional: prismic.LinkField
  /**
   * Left Button Text field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.leftbuttontext
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  leftbuttontext: prismic.KeyTextField
  /**
   * Right Title Optional field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional Title Paragraph
   * - **API ID Path**: content.primary.righttitleoptional
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  righttitleoptional: prismic.RichTextField
  /**
   * Right Image Optional field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.rightimageoptional
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  rightimageoptional: prismic.ImageField<never>
  /**
   * rightHalf field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: right half of the content
   * - **API ID Path**: content.primary.righthalf
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  righthalf: prismic.RichTextField
  /**
   * Right Button Optional field in *Content → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.rightbuttonoptional
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  rightbuttonoptional: prismic.LinkField
  /**
   * Right Button Text field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.rightbuttontext
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  rightbuttontext: prismic.KeyTextField
}
/**
 * HalfHalf variation for Content Slice
 *
 * - **API ID**: `halfHalf`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceHalfHalf = prismic.SharedSliceVariation<
  'halfHalf',
  Simplify<ContentSliceHalfHalfPrimary>,
  never
>
/**
 * Primary content in Content → Primary
 *
 */
interface ContentSliceOneThirdTwoThirdPrimary {
  /**
   * Title field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your SubHeading
   * - **API ID Path**: content.primary.titleContent
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  titleContent: prismic.RichTextField
  /**
   * lefthalf field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Left half of the content
   * - **API ID Path**: content.primary.lefthalf
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  lefthalf: prismic.RichTextField
  /**
   * rightHalf field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: right half of the content
   * - **API ID Path**: content.primary.righthalf
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  righthalf: prismic.RichTextField
  /**
   * Reverse the Row field in *Content → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content.primary.reversethis
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  reversethis: prismic.BooleanField
  /**
   * Background Color Toggle field in *Content → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content.primary.hascolor
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hascolor: prismic.BooleanField
}
/**
 * OneThirdTwoThird variation for Content Slice
 *
 * - **API ID**: `oneThirdTwoThird`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceOneThirdTwoThird = prismic.SharedSliceVariation<
  'oneThirdTwoThird',
  Simplify<ContentSliceOneThirdTwoThirdPrimary>,
  never
>
/**
 * Primary content in Content → Primary
 *
 */
interface ContentSliceQuartersPrimary {
  /**
   * Background Color Toggle field in *Content → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content.primary.hascolor
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hascolor: prismic.BooleanField
  /**
   * Title field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your SubHeading
   * - **API ID Path**: content.primary.titleContent
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  titleContent: prismic.RichTextField
  /**
   * First Quarter Image field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.first_quarter_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  first_quarter_image: prismic.ImageField<never>
  /**
   * First Quarter field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: First Quarter Content
   * - **API ID Path**: content.primary.firstquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  firstquarter: prismic.RichTextField
  /**
   * Button Link First Quarter field in *Content → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Button Link
   * - **API ID Path**: content.primary.buttonlinkfirstquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  buttonlinkfirstquarter: prismic.LinkField
  /**
   * Button Text First Quarter field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button Text
   * - **API ID Path**: content.primary.buttontextfirstquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttontextfirstquarter: prismic.KeyTextField
  /**
   * Second Quarter Image field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.second_quarter_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  second_quarter_image: prismic.ImageField<never>
  /**
   * Second Quarter field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Second Quater content
   * - **API ID Path**: content.primary.secondquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  secondquarter: prismic.RichTextField
  /**
   * Button Link Second Quarter field in *Content → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Button Link
   * - **API ID Path**: content.primary.buttonlinksecondquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  buttonlinksecondquarter: prismic.LinkField
  /**
   * Button Text Second Quarter field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.buttontextsecondquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttontextsecondquarter: prismic.KeyTextField
  /**
   * Third Quarter Image field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.third_quarter_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  third_quarter_image: prismic.ImageField<never>
  /**
   * Third Quarter field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Third Quarter Content
   * - **API ID Path**: content.primary.thirdquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  thirdquarter: prismic.RichTextField
  /**
   * Button Link Third Quarter field in *Content → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.buttonlinkthirdquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  buttonlinkthirdquarter: prismic.LinkField
  /**
   * Button Text Third Quarter field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.buttontextthirdquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttontextthirdquarter: prismic.KeyTextField
  /**
   * Fourth Quarter Image field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.fourth_quarter_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  fourth_quarter_image: prismic.ImageField<never>
  /**
   * Fourth Quarter field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Fourth Quarter Content
   * - **API ID Path**: content.primary.fourthquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  fourthquarter: prismic.RichTextField
  /**
   * Button Link Fourth Quarter field in *Content → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.buttonlinkfourthquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  buttonlinkfourthquarter: prismic.LinkField
  /**
   * Button Text Fourth Quarter field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.buttontextfourthquarter
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttontextfourthquarter: prismic.KeyTextField
}
/**
 * Quarters variation for Content Slice
 *
 * - **API ID**: `quarters`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceQuarters = prismic.SharedSliceVariation<
  'quarters',
  Simplify<ContentSliceQuartersPrimary>,
  never
>
/**
 * Item in Content → Items
 *
 */
export interface ContentSliceResourcesItem {
  /**
   * heading field in *Content → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heading: prismic.TitleField
  /**
   * buttontext field in *Content → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].buttontext
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttontext: prismic.KeyTextField
  /**
   * buttonlink field in *Content → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].buttonlink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  buttonlink: prismic.LinkField
}
/**
 * resources variation for Content Slice
 *
 * - **API ID**: `resources`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceResources = prismic.SharedSliceVariation<
  'resources',
  Record<string, never>,
  Simplify<ContentSliceResourcesItem>
>
/**
 * Slice variation for *Content*
 *
 */
type ContentSliceVariation =
  | ContentSliceDefault
  | ContentSliceHalfHalf
  | ContentSliceOneThirdTwoThird
  | ContentSliceQuarters
  | ContentSliceResources
/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: `Content`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSlice = prismic.SharedSlice<'content', ContentSliceVariation>
/**
 * Primary content in Forms → Primary
 *
 */
interface FormsSliceDefaultPrimary {
  /**
   * Title field in *Forms → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional Title
   * - **API ID Path**: forms.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
}
/**
 * Default variation for Forms Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FormsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FormsSliceDefaultPrimary>,
  never
>
/**
 * Slice variation for *Forms*
 *
 */
type FormsSliceVariation = FormsSliceDefault
/**
 * Forms Shared Slice
 *
 * - **API ID**: `forms`
 * - **Description**: `Forms`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FormsSlice = prismic.SharedSlice<'forms', FormsSliceVariation>
/**
 * Primary content in Heros → Primary
 *
 */
interface HerosSliceDefaultPrimary {
  /**
   * bgImage field in *Heros → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: heros.primary.bgimage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  bgimage: prismic.ImageField<never>
  /**
   * heading field in *Heros → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: heros.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heading: prismic.TitleField
  /**
   * description field in *Heros → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: What are we saying here?
   * - **API ID Path**: heros.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField
  /**
   * buttonLink field in *Heros → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: heros.primary.buttonlink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  buttonlink: prismic.LinkField
  /**
   * buttonText field in *Heros → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heros.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttontext: prismic.KeyTextField
}
/**
 * Default variation for Heros Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HerosSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HerosSliceDefaultPrimary>,
  never
>
/**
 * Slice variation for *Heros*
 *
 */
type HerosSliceVariation = HerosSliceDefault
/**
 * Heros Shared Slice
 *
 * - **API ID**: `heros`
 * - **Description**: `Heros`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HerosSlice = prismic.SharedSlice<'heros', HerosSliceVariation>
/**
 * Default variation for Locations Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LocationsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>
/**
 * Slice variation for *Locations*
 *
 */
type LocationsSliceVariation = LocationsSliceDefault
/**
 * Locations Shared Slice
 *
 * - **API ID**: `locations`
 * - **Description**: `Locations`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LocationsSlice = prismic.SharedSlice<
  'locations',
  LocationsSliceVariation
>
/**
 * Primary content in MenuItem → Primary
 *
 */
interface MenuItemSliceDefaultPrimary {
  /**
   * LinkText field in *MenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.linktext
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  linktext: prismic.KeyTextField
  /**
   * LinkTarget field in *MenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.linktarget
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  linktarget: prismic.LinkField
}
/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MenuItemSliceDefaultPrimary>,
  never
>
/**
 * Primary content in MenuItem → Primary
 *
 */
interface MenuItemSliceMenuItemWithDropdownPrimary {
  /**
   * LinkText field in *MenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.linktext
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  linktext: prismic.KeyTextField
}
/**
 * Item in MenuItem → Items
 *
 */
export interface MenuItemSliceMenuItemWithDropdownItem {
  /**
   * LinkText field in *MenuItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].linktext
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  linktext: prismic.KeyTextField
  /**
   * LinkTarget field in *MenuItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].linktarget
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  linktarget: prismic.LinkField
}
/**
 * MenuItemWithDropdown variation for MenuItem Slice
 *
 * - **API ID**: `menuItemWithDropdown`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuItemSliceMenuItemWithDropdown = prismic.SharedSliceVariation<
  'menuItemWithDropdown',
  Simplify<MenuItemSliceMenuItemWithDropdownPrimary>,
  Simplify<MenuItemSliceMenuItemWithDropdownItem>
>
/**
 * Slice variation for *MenuItem*
 *
 */
type MenuItemSliceVariation =
  | MenuItemSliceDefault
  | MenuItemSliceMenuItemWithDropdown
/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: `MenuItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuItemSlice = prismic.SharedSlice<
  'menu_item',
  MenuItemSliceVariation
>
/**
 * Primary content in Separator → Primary
 *
 */
interface SeperatorSliceDefaultPrimary {
  /**
   * Need A Dividor? field in *Separator → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: seperator.primary.need_a_dividor
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  need_a_dividor: prismic.BooleanField
}
/**
 * Default variation for Separator Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SeperatorSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SeperatorSliceDefaultPrimary>,
  never
>
/**
 * Slice variation for *Separator*
 *
 */
type SeperatorSliceVariation = SeperatorSliceDefault
/**
 * Separator Shared Slice
 *
 * - **API ID**: `seperator`
 * - **Description**: `Seperator`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SeperatorSlice = prismic.SharedSlice<
  'seperator',
  SeperatorSliceVariation
>
declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }
  namespace Content {
    export type {
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      HomepageDocument,
      MainmenuDocumentData,
      MainmenuDocumentDataSubmenuItem,
      MainmenuDocumentDataSlicesSlice,
      MainmenuDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      SitemetadataDocumentData,
      SitemetadataDocument,
      SubdirectoryDocumentData,
      SubdirectoryDocument,
      AllDocumentTypes,
      CarousellSliceDefaultPrimary,
      CarousellSliceDefaultItem,
      CarousellSliceDefault,
      CarousellSliceVideoCarouselPrimary,
      CarousellSliceVideoCarouselItem,
      CarousellSliceVideoCarousel,
      CarousellSliceLocationsItem,
      CarousellSliceLocations,
      CarousellSliceLocationMembersItem,
      CarousellSliceLocationMembers,
      CarousellSliceVariation,
      CarousellSlice,
      ContentSliceDefaultPrimary,
      ContentSliceDefault,
      ContentSliceHalfHalfPrimary,
      ContentSliceHalfHalf,
      ContentSliceOneThirdTwoThirdPrimary,
      ContentSliceOneThirdTwoThird,
      ContentSliceQuartersPrimary,
      ContentSliceQuarters,
      ContentSliceResourcesItem,
      ContentSliceResources,
      ContentSliceVariation,
      ContentSlice,
      FormsSliceDefaultPrimary,
      FormsSliceDefault,
      FormsSliceVariation,
      FormsSlice,
      HerosSliceDefaultPrimary,
      HerosSliceDefault,
      HerosSliceVariation,
      HerosSlice,
      LocationsSliceDefault,
      LocationsSliceVariation,
      LocationsSlice,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceDefault,
      MenuItemSliceMenuItemWithDropdownPrimary,
      MenuItemSliceMenuItemWithDropdownItem,
      MenuItemSliceMenuItemWithDropdown,
      MenuItemSliceVariation,
      MenuItemSlice,
      SeperatorSliceDefaultPrimary,
      SeperatorSliceDefault,
      SeperatorSliceVariation,
      SeperatorSlice,
    }
  }
}
