// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  carousell: dynamic(() => import('./Carousell')),
  content: dynamic(() => import('./Content')),
  forms: dynamic(() => import('./Forms')),
  heros: dynamic(() => import('./Heros')),
  locations: dynamic(() => import('./Locations')),
  menu_item: dynamic(() => import('./MenuItem')),
  seperator: dynamic(() => import('./Separator')),
}
